version: '3'

services:

  zookeeper:
    image: 'bitnamilegacy/zookeeper:3.8'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnamilegacy/kafka:3.5'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # BASIC CONFIG
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

      # LISTENERS
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:9092

      # ADVERTISED LISTENERS
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:29092,EXTERNAL://xx.xxx.x.x:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

      # PARTITIONS
      - KAFKA_CFG_NUM_PARTITIONS=4

      # RETENTION POLICY
      - KAFKA_CFG_LOG_RETENTION_MS=86400000          # 1 Day
      - KAFKA_CFG_LOG_RETENTION_BYTES=6000000000     # 6 GB

      # REPLICATION (SINGLE NODE)
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
